SPLASHES = [
    'Sexy!',
    'We Fixed The Rail!',
    'Teh',
    'Who Broke The Rail?',
    'The Work Of Notch!',
    'The World Of Notch!',
    'WDYM Discontinued?',
    'Oh, OK, Pigmen...',
    'Check Out The Non-Existant Far Lands!',
    'mcpi.tk!',
    'Come Back @Alvarito!',
    'Classic!',
    'Wow! Modded MCPI!',
    'Now With Fly-Hacks!',
    'Where Is My Pie?',
    'I Was Promised Pie!',
    '@Banana',
    'BANANANA!!',
    'to na or not to na, that is the question!'
    'Not Minecraft Java!',
    'Not Minecraft Bedrock (Technically)!',
    'Definitely Not Minecraft Console!',
    'Oh Yeah, That Version...',
    'Join The Discord!',
    'Segmentation fault',
    'Segmentation fault (core dumped)',
    'qemu: uncaught target signal 11 (Segmentation fault) - core dumped',
    'It\'s The Segment\'s Fault!',
    'As Seen On Discord!',
    'Obfuscated!',
    'As Not Seen On TV!',
    'Why Must You Hurt Me?',
    'Who Is StevePi?',
    'Made By Notch!',
    'Open-Source!',
    'FREE!',
    'RIP MCPIL-Legacy, you lived a good life'
]
